title: "CtRL-Sim: Reactive and Controllable Driving Agents with Offline Reinforcement Learning"
description: TODO Presenting a novel architecture for sequence-modelling of sets.<br>Work by <a href="https://www.wikiwand.com/en/Luke_Rowe">Luke Rowe</a>, <a href="https://pbs.twimg.com/profile_images/1506661208572706820/vY2klztu_400x400.jpg">Roger Girgis</a>, <a href="https://www.wikiwand.com/en/Anthony_Gosselin">Anthony Gosselin</a>, <a href="https://mila.quebec/en/person/bruno-carrez/">Bruno Carrez</a>, <a href="https://fgolemo.github.io/">Florian Golemo</a>, <a href="https://algolux.com/our-team/felix-heide/">Felix Heide<a/>, <a href="https://liampaull.ca/">Liam Paull</a>, <a href="https://sites.google.com/view/christopher-pal">Christopher Pal</a>
theme: jekyll-theme-cayman
links:
  arxiv: TODO
  code: TODO
