title: CtRL-Sim: Reactive and Controllable Driving Agents with Offline Reinforcement Learning
description: TODO Presenting a novel architecture for sequence-modelling of sets.<br>Work by <a href="https://pbs.twimg.com/profile_images/1506661208572706820/vY2klztu_400x400.jpg">Roger Girgis</a>, <a href="https://fgolemo.github.io/">Florian Golemo</a>, <a href="https://www.codevilla.info/">Felipe Codevilla</a>, <a href="http://martincsweiss.com/">Martin Weiss</a>, <a href="https://jimaldon.com/about.html">Jim Aldon D'Souza</a>, <a href="https://saebrahimi.github.io/">Samira Ebrahimi Kahou</a>, <a href="https://algolux.com/our-team/felix-heide/">Felix Heide<a/>, <a href="https://sites.google.com/view/christopher-pal">Christopher Pal</a>
theme: jekyll-theme-cayman
links:
  arxiv: TODO
  code: TODO
